### ISSUE TITLE
Missing keyword highlighting

### ISSUE THREAD

**Issue by alexheretic** [atom/language-rust#2]
The following keywords are not currently handled
* `self`: `use self::foo`
* `super`: `use super::foo;`
* `crate`: `use crate::foo`
* `dyn`: `fn foo() -> Box<dyn std::fmt::Display>`
* `in`: `for number in &[1, 2, 3] {}`
* `as`: `let float = 123 as f32;`

**Comment by maxbrunsfeld** [comment]
Thanks for the report. Should be fixed on master.

**Comment by alexheretic** [comment]
Great thanks. I'm not seeing `as` highlighting, but the rest look good now.
![](https://user-images.githubusercontent.com/2331607/47148734-62a46300-d2c9-11e8-9733-e86703247ed1.png)

**Comment by alexheretic** [comment]
Also another example of visibility usage that isn't highlighted.
```rust
pub(crate) struct Foo {
    pub(super) bar: i32, 
}
```
![vis-atom](https://user-images.githubusercontent.com/2331607/47151163-e877dc80-d2d0-11e8-84fe-6cce7bf686f3.png)
