### ISSUE TITLE
`self` highlighting

### ISSUE THREAD

**Issue by alexheretic** [atom/language-rust#3]
`self` usage in function definitions is highlighted differently from other arguments elsewhere, so perhaps it should be here too.

### Rust doc source
![rustdoc-self](https://user-images.githubusercontent.com/2331607/47154183-81aaf100-d2d9-11e8-9059-4860d26b9104.png)

### Github markdown
```rust
pub fn get<I>(&self, index: I) -> Option<&I::Output>
    where I: SliceIndex<Self>
{
    index.get(self)
}
```

### atom/language-rust
![atom-rust-self](https://user-images.githubusercontent.com/2331607/47154191-853e7800-d2d9-11e8-9e15-8eb4b917de4d.png)

**Comment by maxbrunsfeld** [comment]
Thanks for pointing these issues out @alexheretic! This is fixed on master of Atom. I'm going to archive this repository now, as we've mode its contents into Atom core.
